
authToken.header=${AUTH_TOKEN_HEADER:Authorization}

#JWT authentication configuration for sm-shop
jwt.header=${JWT_HEADER:Authorization}
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:604800}
jwt.grace-period-seconds=${JWT_GRACE_PERIOD_SECONDS:200}




