#GMail sample configuration
#May require a keystore for certificates
mailSender.protocol=smtps
mailSender.host=smtp.gmail.com
mailSender.port=587
mailSender.username=iamskk1@gmail.com
mailSender.password=djviwzackrsiyphqasad
mailSender.mail.smtp.auth=true
mail.smtp.starttls.enable=true
#mail.smtp.starttls.required=true

#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=iamskk1@gmail.com
#spring.mail.password=djviwzackrsiyphq
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true
